table artemis_supply_risk
	lineageTag: e26fea78-5f38-5ac1-96b8-887f53094e88

	measure 'High Risk Materials' = CALCULATE(COUNTROWS('artemis_supply_risk'), 'artemis_supply_risk'[risk_tier] = "High")
		formatString: #,##0
		lineageTag: 154dc751-03ec-5821-be20-0cb6b88872d4

	measure 'Critical Slips >30d' = CALCULATE(COUNTROWS('artemis_supply_risk'), 'artemis_supply_risk'[criticality] = "Critical", 'artemis_supply_risk'[sole_source] = TRUE, 'artemis_supply_risk'[avg_delay_days] > 30)
		formatString: #,##0
		lineageTag: 0f94df55-a134-5f79-9613-fd6b6f64c4ec

	measure 'Sole-Source Exposure ($)' = CALCULATE(SUM('artemis_supply_risk'[total_committed_usd]), 'artemis_supply_risk'[sole_source] = TRUE)
		formatString: \$#,##0
		lineageTag: 9c954030-2060-573e-9092-4a8daaf6d7b6

	measure 'Pad Anomalies' = SUM('artemis_supply_risk'[pad_anomalies])
		formatString: #,##0
		lineageTag: f5bb33f2-1631-577e-81cd-13afdf6dc008

	measure 'Avg Delay (days)' = AVERAGE('artemis_supply_risk'[avg_delay_days])
		formatString: #,##0.0
		lineageTag: a74871b2-5b55-5111-b999-b05526f6bfe9

	measure 'Material Count' = COUNTROWS('artemis_supply_risk')
		formatString: #,##0
		lineageTag: c19a8d1c-41fb-54b8-8231-ec999747875f

	column program
		dataType: string
		lineageTag: 2b8376f9-6c1c-550e-adab-102acfd6c4be
		summarizeBy: none
		sourceColumn: program

	column material_id
		dataType: string
		lineageTag: 30ed7b6b-8421-5397-8c36-42815db6f0b3
		summarizeBy: none
		sourceColumn: material_id

	column material_name
		dataType: string
		lineageTag: 2c46e4e3-db72-5716-94e8-f07c6b78d8be
		summarizeBy: none
		sourceColumn: material_name

	column criticality
		dataType: string
		lineageTag: f10a8ed1-fac6-5c73-b3f5-25ed970d33e5
		summarizeBy: none
		sourceColumn: criticality

	column sole_source
		dataType: boolean
		lineageTag: e2e8a811-eae9-56a6-a760-76120ed4fd8e
		summarizeBy: none
		sourceColumn: sole_source

	column avg_delay_days
		dataType: double
		lineageTag: f68fee5a-ec8c-54b9-a134-a3ca4e19f068
		summarizeBy: none
		sourceColumn: avg_delay_days

	column risk_score
		dataType: int64
		lineageTag: 59f75597-c9ea-547b-bc98-c9fcc1deb451
		summarizeBy: none
		sourceColumn: risk_score

	column risk_tier
		dataType: string
		lineageTag: 69f9405d-e895-5d0d-91db-322ddf029b70
		summarizeBy: none
		sourceColumn: risk_tier

	column vendor_name
		dataType: string
		lineageTag: 45fe42f5-79fa-5638-9f84-7c7b02be53eb
		summarizeBy: none
		sourceColumn: vendor_name

	column cage_code
		dataType: string
		lineageTag: e9e24d2a-3420-5264-9071-9944dbcbb538
		summarizeBy: none
		sourceColumn: cage_code

	column past_perf_score
		dataType: double
		lineageTag: 7d74feca-7e87-5f85-8856-0c3188ebe009
		summarizeBy: none
		sourceColumn: past_perf_score

	column total_committed_usd
		dataType: double
		lineageTag: bb753543-31e5-57dd-82e2-476ec4952bbf
		summarizeBy: none
		sourceColumn: total_committed_usd

	column po_count
		dataType: int64
		lineageTag: 9ddab6a0-ed58-540f-8250-d12f09c67597
		summarizeBy: none
		sourceColumn: po_count

	column pad_anomalies
		dataType: int64
		lineageTag: bc5dd574-8aa7-5a44-ac46-bee905433058
		summarizeBy: none
		sourceColumn: pad_anomalies

	partition artemis_supply_risk = m
		mode: directQuery
		source =
				let
				    Source = Databricks.Catalogs(DatabricksServerHostname, DatabricksHttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    Catalog = Source{[Name=CatalogName, Kind="Database"]}[Data],
				    Schema = Catalog{[Name="gold", Kind="Schema"]}[Data],
				    Data = Schema{[Name="artemis_supply_risk", Kind="Table"]}[Data]
				in
				    Data

